name: beatdetectionenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.40
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.12
      - debugpy==1.8.11
      - decorator==4.4.2
      - defusedxml==0.7.1
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - grpcio==1.69.0
      - guppy3==3.1.5
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - ipykernel==6.29.5
      - ipympl==0.9.6
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - memory-profiler==0.61.0
      - mistune==3.1.0
      - mne==1.9.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - neurokit2==0.2.10
      - nir==1.0.4
      - nirtorch==1.0
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.3.5
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pyqtgraph==0.13.7
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pywavelets==1.8.0
      - pywin32==308
      - pywinpty==2.0.14
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - snntorch==0.9.1
      - soundfile==0.13.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - torch-geometric-temporal==0.54.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-tb-profiler==0.4.3
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wfdb==4.1.2
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
